### PR TITLE
Add support for CSO compressed files

### PR DESCRIPTION
**Pull request by unknownbrackets**
I don't have UltraISO, and searching for isz casually didn't yield any alternative compressors.  Since I already [wrote a CSO compressor](https://github.com/unknownbrackets/maxcso) for PPSSPP (though there are many slower ones available), I figured it'd be pretty easy to add support for CSO files.

CSOs are block based and fairly simple.  Some tools may not be able to handle > 4GB files, since PSP games could not be larger than 1.8GB, but this patch can, and so can maxcso (well, after a fix I just made to it.)

IMHO it might be nice to put the different ImageStreams into their own directory, though.

(this implementation is mostly just PPSSPP's implementation, although that one reads full sectors so I changed some things.  It also has larger disk reads when reading more bytes, but I didn't port that over yet.)

-[Unknown]

### CODE REVIEW

**Comment by unknownbrackets** [comment]
Let me know if there's anything you'd like changed or if you're not sure this is a good format to use.  It's a fairly generic and simple ISO compression method, even if it's mostly only common with PSP ISOs right now.

I do think it's good to have some alternative format that doesn't require paid software to create.

-[Unknown]

**Comment by jpd002** [comment]
Testing your changes as we speak. I think it's a good idea to add support for CSOs. I chose to support ISZs a while back because their format was documented and because you can use the trial version to compress disk images without any limitation. But yeah, tools to create CSOs are free, so, it's easier for everyone.

At first glance, the code looks good, but I'll probably do a quick refactor to make it match the code style of the rest.

**Comment by unknownbrackets** [comment]
Oh, I saw it was a trial and assumed it was time limited or something.  I've never used the software.

-[Unknown]

**Comment by unknownbrackets** [comment]
Changed those things.

-[Unknown]

**Comment by jpd002** [comment]
Yup, no space between `if` and `()` and no single-line ifs. Also, tabs everywhere, initialization of class members in headers as much as possible and `*` besides the type name and not the member name.

**Comment by unknownbrackets** [comment]
All indentation is already tabs (well, except the one I changed in a838a2b7d9986e7a0137f70acc4d0190a57848bc to match the rest of the file.)  Alignment is spaces, do you use tabs even for alignment against non-tabs?

-[Unknown]

**Comment by jpd002** [comment]
Yes, I use tabs also for alignment. Also, it would probably be better for virtual functions in that class (minus the destructor) to have override specifiers.

**Comment by unknownbrackets** [comment]
Well, IszImageStream.h seems to use spaces, even for indentation actually.  Doesn't matter.  I've added overrides there too.

-[Unknown]

**Comment by jpd002** [comment]
Thanks. Yeah, I need to clean that piece of code, it should be tabs there too. 

Going to do a last test with a dual layer disc image and I will merge after.

**Comment by jpd002** [comment]
Dual Layer test passed successfully. Thanks for the pull request!

**Pull request merged**
