### PR TITLE
Android: MultiOS Build Support

### PR DESCRIPTION
**Pull request by Thunder07**
I don’t run Windows or Mac so I couldn’t verify if this works, but I did download the SDKs/NDK so the paths are correct.
just need you to verify that Darwin for Mac & CYGWIN for windows work.

Edit: I've also sent pull requests to the other projects for the same fixes.

### CODE REVIEW

**Comment by LoungeKatt** [comment]
You could probably eliminate ANDROID_SDK_ROOT and ANDROID_NDK_ROOT since they should be part of PATH.

**Comment by Thunder07** [comment]
Probably, would also need to append the build instructions to reflect that.

**Comment by Thunder07** [comment]
I guess this is obsolete with the new arrangement.

**Comment by LoungeKatt** [comment]
You could repurpose it for a master build script.

**Comment by Thunder07** [comment]
you already have that covered.
unless you (@jpd002) still plan on keeping each build separate.

**Comment by LoungeKatt** [comment]
I meant you could combine it into one script for the master project. The one I was messing around with somehow gets a ../ off when it builds everything at once, even though each project builds separately.

**Comment by Thunder07** [comment]
I put this together https://github.com/Thunder07/Play-Build/tree/scripts

**Comment by jpd002** [comment]
Nice! I think it the scripts should go inside a `build_android` folder though, because we might have scripts for other platforms at some point.

**Comment by Thunder07** [comment]
Ya i was thinking about this.
I was thinking taking the script a step further, ./build.sh *OS* *Release_Type*
this will allow it to support multiple OS using one scipt and it can remain in the root directory of the project.

**Comment by Thunder07** [comment]
just pushed this https://github.com/Thunder07/Play-Build/commit/38a818b9354ba659054bb6a31af2e2a2202e8f90
a single script to build debug, release & clean but as it stands it only supports android, not sure how you're getting the other platforms build, so I've used placeholders for now.

**Comment by Fadi5555** [comment]
I have a question.
What is multiOS build? Is that a process for multi platforms?
Also is this thing will include an iOS port? Because it's named (multiOS)?

**Comment by Thunder07** [comment]
no, this will just allow the project to be build on different OS(operating systems), such a windows, mac & linux.

**Comment by Fadi5555** [comment]
@Thunder07 thanks for answer.
Well, that's a good idea. But the OS like win, Mac, Linux all these already have a ps2 emu (PCSX2) so in my opinion we should focus on mobile OS like Android / iOS. Because the didn't have a ps2 emu yet.

Anyway the creator @jpd002 doing his best to makes his project has more compatibility.
Also if there a good developers like you and @LoungeKatt who have more knowledge about these stuff.
The project will be more than playable and stable as well.
Working as a team will be useful and the reason for successes of any project.

**Comment by Thunder07** [comment]
This is not what this is for, this allows you to build Play! for anything (android, ios, windows, macosx) but allows you to do it on windows, macosx and linux.

which devices or games the dev chooses to fix/support first is of his own accord.

**Comment by Fadi5555** [comment]
Oh I got your point now
Thanks for explaining that for me.
Yeah absolutely this is a good idea indeed for fixing the issues on play!

**Pull request closed without merging**
