### PR TITLE
Add PwrOff IOP module stub

### PR DESCRIPTION
**Pull request by kernle32dll**
Makes ScummVM boot, if LIBSD is provided in rom0

### CODE REVIEW

**Comment by uyjulian** [comment]
ps2sdk is full of hooks, and poweroff modules is one of them.  
I think it's fine to patch/HLE the stuff that hooks.

**Comment by jpd002** [comment]
Agreed, I think it has its place in the emulator. I think we should just be careful to only enable our HLE version if we figure out that the ELF is trying to load that module, just to avoid a conflict in the case a game uses SIF RPC server id 0x09090900.

**Comment by kernle32dll** [comment]
> Is the ELF making any attempt at loading a POWEROFF module? Isn't it bundled with a compiled version of this: https://github.com/ps2dev/ps2sdk/tree/master/iop/dev9/poweroff ?

That is an excellent question, I was asking myself. The thing I'm trying to get running is version 1.7.0 (last version with PS2 support) of [ScummVM](https://www.scummvm.org/). It does come with a precompiled `POWEROFF.IRX`. However, from what I can tell, the ELF does not even try to load that module. Hence I was under the impression it might be BIOS bundled - which is of course silly (*facepalm*).

**Comment by uyjulian** [comment]
It may be loaded by SifLoadModuleBuffer

**Comment by kernle32dll** [comment]
I looked into the source code a bit further, and I found what is happening. So, if the ELF detects being run from `host:`, it skips loading (amongst other things) `POWEROFF.IRX`. @jpd002 suspects that this could be due to for the ELF to be run via `host:`, it needs to be e.g. loaded by ps2link - which loads `POWEROFF.IRX` itself. Would this module be kept loaded, when ps2link loads the ELF @uyjulian?

**Comment by uyjulian** [comment]
As long as the IOP is not rebooted, `POWEROFF.IRX` will be kept loaded. ps2link does not reboot the IOP itself.

**Comment by jpd002** [comment]
Thanks for the confirmation @uyjulian.

Fair enough then, I guess it makes sense to have this in the emulator in its current form. 

Having a ELF/homebrew "runtime environment" is a good idea for the future, we could have something to load some HLE modules specifically in the "Boot ELF" scenario.

**Comment by jpd002** [comment]
Thanks for this!

**Pull request merged**
