### PR TITLE
Bringing iOS up to current standards

### PR DESCRIPTION
**Pull request by LoungeKatt**
Just putting this here for testing purposes.

### CODE REVIEW

**Comment by jpd002** [comment]
Looks promising! I won't have time to test it today, but I'll give it a try ASAP.

**Comment by LoungeKatt** [comment]
There's no rush. The controls don't function yet but the groundwork is there.

**Comment by Fadi5555** [comment]
Wow that's really amazing.
Nice job...

**Comment by LoungeKatt** [comment]
image1

**Comment by Fadi5555** [comment]
Wow wow wow.
I really want to cry. That's really AMAZING. You not just add the cover image of games no and also bring introduced the short information of games. All games have its own introduced info.
You're a ROCK. So far was fabulous. I hope you can make on landscape mode as well as you said above.
Nice job. Really like it so much.

**Comment by LoungeKatt** [comment]
@jpd002 While the final decision is your (of course), I put up a vote on how to go about the iOS layout at https://plus.google.com/110545364035768725477/posts/NQuDKPgWf2F

I also posted a few samples to compare two of the three (grid and list) at https://plus.google.com/110545364035768725477/posts/N7wf8c8prWS

Personally, I would do a hybrid of the grid in portrait and list in landscape, but that's me.

**Comment by LoungeKatt** [comment]
This still needs a shared array of the files (similar to Android's method for handling rotation) and an image cache. Honestly, the image cache is only for data, though. SDWebImage already has all the lazy load and memory cache covered and still does it faster than the best loafers on Android.

**Comment by Fadi5555** [comment]
You're brilliant. Nice job.
About @jpd002 I'm sure when he see it will feel happy about it. Because you already helped him on his project.

Other thing well I goes to website an saw all 4 pictures. Well on myself I like the picture of images of games with details. Really amazing it gives you a short info of it.

Also you said above SDWebImage on iOS open faster than android? So according to this, are we need an Internet to show that images of games every time we open it or just the first time? Thanks.

**Comment by Fadi5555** [comment]
I wasn't to tell you other thing important.
The current version of play! When I open it. It doesn't show me the ps2 isos/bins/cso etc. no it shows me all the isos of ps1/psp all them because I have ppsspp as well as retroarch so I have the games of them.
Well I mean here if we can put the specific path of folder which is contain psp games it well be more than good.

**Comment by LoungeKatt** [comment]
@Fadi5555 This isn't really the place to respond to the poll and you're requesting something that was already done. This isn't the place for requests, though.

**Comment by Fadi5555** [comment]
@LoungeKatt I'm really sorry I didn't mean that.
I just want to tell you something related to that.

**Comment by LoungeKatt** [comment]
@Fadi5555 I appreciate your gratitude, but it is a little overwhelming.

**Comment by Fadi5555** [comment]
Believe me all what I said to you was the truth.
Also you did all that to us so it's really appreciated so much.
I'll be always waiting for all the new from you patiently.
Keep going.

**Comment by LoungeKatt** [comment]
@Fadi5555 It's all opinion. This may be annoying to @jpd002 because he had other plans and this got in his way. You don't know. I don't know. I can say patient is the last thing I would call it.

**Comment by Fadi5555** [comment]
You're absolutely right about opinions.
But I'm sure @jpd002 will feel a proud of you.
Because if you didn't do that he'll do it soon or later but sometime he did have enough time to do android as well as iOS. So about me that's really helpful things.
Don't worry we'll waiting for merging all what you have done it so far.

**Comment by Fadi5555** [comment]
I'm really wondering why @jpd002 didn't merge this until now? Hmmm

**Comment by LoungeKatt** [comment]
@Fadi5555 It isn't ready and hasn't been tested.

**Comment by jpd002** [comment]
Sorry, I didn't get much time to test this. I'll try it next week.

**Comment by LoungeKatt** [comment]
@jpd002 No big deal. More time to get closer to being identical.

**Comment by Fadi5555** [comment]
Oh I thought you already test it @LoungeKatt because you show us the progress as well as some images from it?

@jpd002 it's ok. But you really how to test it if you have a free time any day.

**Comment by LoungeKatt** [comment]
@Fadi5555 I did test it, but I mean for public testing. @jpd002 will get to it when he can. It's not a life or death matter. It ends up being more time to make sure it's perfect when he does.

**Comment by Fadi5555** [comment]
100% right.

**Comment by LoungeKatt** [comment]
@jpd002 I know I'm not splitting this into individual PRs by what it is, but it is mostly iOS versions of existing Android changes. I can split it up, but I figured it's not really a matter of "should we" so much as "how do we"

**Comment by Fadi5555** [comment]
@LoungeKatt nice job.
It's matter of time to test it by @jpd002 and merge it.

Don't worry. You're not split this into individual. You just helped him and save his time. Again and again all what you have done so far is FANTASTIC. About me: I really feeling a proud of you as well as the others including @jpd002 himself.

**Comment by LoungeKatt** [comment]
@Fadi5555 ... Is it ok if @jpd002 speaks for himself? It's his project, after all.

**Comment by Fadi5555** [comment]
I just give you my opinion about that.
But anyway  you're right. Sorry.

**Comment by Fadi5555** [comment]
@LoungeKatt isn't there any new improvement for iOS?

**Comment by jpd002** [comment]
So, I finally got around testing this branch. 

First, I try to keep all build settings in `GeneralSettings.xcconfig`, so, the project file shouldn't have changes to build flags. I actually had some issues building the branch without any changes, but I was able to get it to work again by removing the changes to the project and adding the `Play!` path in the framework search directories. (https://github.com/jpd002/Play-/commit/8928795098e77042c80b957c711fece9b96bf80f)

Then, there seem to be some rendering issues with the disk selection view:

Portrait:
img_0308

Landscape:
img_0309

Landscape (slight scrolling):
img_0310

I don't know what is causing this, I haven't really looked into it yet.

**Comment by Fadi5555** [comment]
@jpd002 thanks for testing and telling that to us. Well I think @LoungeKatt will gonna help you with this because he did this additions.

Other thing after testing this is the buttons show on you or still missing?

**Comment by LoungeKatt** [comment]
Is there supposed to be a "!" in the path?

And you removed ```OTHER_LDFLAGS = "-ObjC";``` with that change. That could be some of the issue you are having.

You may be keeping build settings there, but what I added was actually the default inclusion of the project path. I didn't even add it, Xcode did. I just didn't move it.

**Comment by Fadi5555** [comment]
@LoungeKatt that's really helpful information.
I guess he facing some issues because of removing something like: OTHER_LDFLAGS = "-ObjC";

**Comment by LoungeKatt** [comment]
@Fadi5555 It's ok if you don't comment on each post. It only ends up making it harder to dig through all the posts for useful information.

@jpd002 I replaced all the internal Xcode frameworks with the ones from Xcode 6.4. I have a feeling part of the issue may be that only the ones I added were from iOS 8.4, so half of them showed as the originals and half as new. This way, you should be able to replace all of them with the ones from your Xcode and it will fix the links. I can't add the older ones because it uses the hash, which I don't have.

**Comment by Fadi5555** [comment]
@LoungeKatt as you like.
Thanks again for all what you have done so far.

**Comment by jpd002** [comment]
The `-ObjC` flag is added here: https://github.com/jpd002/Play-/blob/master/build_ios/GeneralSettings.xcconfig#L11

It's been a while since I've opened the project from a fresh working copy, so you might be right. I'll have to give that a try to see what happens. I'll try the changes to the frameworks and tell you if I get a different result.

**Comment by LoungeKatt** [comment]
Alright. That should load it then. I don't know any other reason it would be so off. Unlike Android, the frameworks were the only difference between what I was testing locally and what was pushed to the PR.

**Comment by Fadi5555** [comment]
@jpd002 it's almost fixes now and ready to merge them.

**Comment by Fadi5555** [comment]
@LoungeKatt Sorry to make it twice.
@jpd002 I really hope to merge that before releasing the weekly build because it brings some features to it. As you know so far it's only has a feature to read iso,bin,isz etc not more than that.
So for that I was telling that to you if you don't mind.
Thanks again for you hard work and time as well.

**Comment by jpd002** [comment]
Ok, I gave that another try and took some time to see why it wasn't working on my side. In my `Documents` folder, I've got 5 files: 3 disk images and 2 ELFs.

So, basically, in the cover view, if a file doesn't have a entry with a valid "boxart" element (which is the case for 4 of my files), no image is shown (not even the default boxart.png) (https://github.com/jpd002/Play-/pull/296/files#diff-6fcb158c3a809b245c7456f1cb8e9fd3R133). That's why I was seeing only Gradius V's box art in there. It also seems that we can only scroll the list down if we have a finger on a box art (doesn't work if we touch an empty space).

Also, I think we should only have the cover view in there. Having both views doesn't serve much purpose and I would prefer making the iOS version as close to the Android version.

**Comment by LoungeKatt** [comment]
I added an extra null check and the initialization shouldn't have been inside that check to begin with, but that probably happened because the check was added after testing the code to display an image.

I tossed the detail view, but there is only so much "like Android" it can look. Very few of the iDevices have both decent hardware and a decent size screen for all that BS going into just listing some files.

**Comment by jpd002** [comment]
Thanks, this is working well now. Did you have any plans to display the filename of "unrecognized" disk images over the default box art?

**Comment by LoungeKatt** [comment]
I was thinking about that last night. Right now it uses the default cell so I need to switch to a custom layout or it'll slap them on everything under the image.

**Comment by jpd002** [comment]
Alright, well, once this will have the disc image name displayed on top of the box art, I'll merge it into master.

**Comment by Fadi5555** [comment]
That's nice.
Also if you could add fps counter like on android it'll be great at least to know the process of games.

**Comment by LoungeKatt** [comment]
Rebased and labels added. Got a little occupied adding DCUO support to Siri on Android LOL.

**Comment by Fadi5555** [comment]
@LoungeKatt hi there
Well I know it's three days but it was long without anything new from you as well as @jpd002.

Other thing what is DCUO?
Last thing jpd002 said:
 (Alright, well, once this will have the disc image name displayed on top of the box art, I'll merge it into master)
What's is that? Also can you do it as a kind of help him? Because if this done he will merge all your amazing commits.

**Comment by LoungeKatt** [comment]
I have no idea what you're asking.

**Comment by Fadi5555** [comment]
Sorry. Well I'll make more clear in two parts of questions:

1- you said (DCUO). So what is it?

2- just see @jpd002 last comment here. He talk about something if is done he will gonna merge all your commits.

Thanks.

**Comment by LoungeKatt** [comment]
DC Universe Online

It's done.

**Comment by Fadi5555** [comment]
Wow that really fantastic.

This is not new from you. Thank you so much for doing all that.
I can't wait to see all your commits gonna merge them.

Thanks again for your hard work.

**Comment by Fadi5555** [comment]
@jpd002 hi there.
I just want to tell you that thing you have mentioned above is done.
It's time to merge them if you don't mind.
Thanks.

**Comment by LoungeKatt** [comment]
Relax. Project owners are notified when pulls update.

**Comment by jpd002** [comment]
I'll take a look this week. I'm currently abroad, so my time is even more limited at the moment (but going back to normal next week).

**Comment by LoungeKatt** [comment]
@jpd002 No rush. It's not going anywhere :)

**Comment by Fadi5555** [comment]
@jpd002 if you have a free time please don't forget to look at these commits and try to merge it.
I know your time is limited but we waiting to this for weeks.
Anyway I'll be waiting patiently.

**Comment by jpd002** [comment]
@LoungeKatt Do you have any objections if I remove this line: https://github.com/AbandonedCart/Play-/blob/iOS-WIP/Source/ui_ios/CoverViewController.m#L146? On my side, I'm getting a crash when selecting an item in the list because the segue is performed twice (no clue why it happens now though). If that's good, I'll do the change and merge that branch in master.

**Comment by Fadi5555** [comment]
@jpd002 good to hear that.
Thank you so much for your time.

Other thing: what is profiler? And is it solve some games with black screen?
Also could uou please add it to ios as well?

Thanks a lot

**Comment by jpd002** [comment]
@Fadi5555 The profiler is just a way to see where CPU time is spend while emulating games. It's only a tools to help with optimizations. There's not much point on adding it to iOS for now.

**Comment by Fadi5555** [comment]
I thought it's important to enhancing games compatibility?

Also if you could add fps to see the speed of games. It will be good.

Anyway waiting for merging them.

**Comment by LoungeKatt** [comment]
I think that's an issue with the storyboard having a selection segue. If so, that is the one to remove to prevent corruption when selecting items.

**Comment by jpd002** [comment]
@LoungeKatt Humm, well, now, since there's no segue, an exception is thrown when selecting an item. I think having the segue on selection was good and the only problem was that it was performed in `didSelectItemAtIndexPath` while it's being done automatically by UIKit just before that selector is invoked.

**Comment by LoungeKatt** [comment]
There is still a segue just in code. It must be a version-specific issue. I haven't gotten either crash.

**Comment by Fadi5555** [comment]
@LoungeKatt hi there sorry for late replay.
Well. You said the android doesn't have profiling tools like iOS
Is that mean iOS is already have profiler? Because it's already added to android by @jpd002.

Other thing jpd002 is talk about something will fix all issues of black screen on games. He said it above just go and see. I's something like EE emulation and VU.
Please tell me what is that actually?

**Comment by jpd002** [comment]
@LoungeKatt Humm, it's really odd that you've never had those crashes. In any case, it works good now, I'm going to merge that branch.

@Fadi5555 The profiler might be added at some point in the future, but for now, I will focus on optimizations that will help both Android and iOS. "Black screen" issues are due to incomplete emulation and every game have their own specific problem, so, it will take a long time before they are all fixed.

**Pull request merged**
