### PR TITLE
Donation

### PR DESCRIPTION
**Pull request by SweetGTA**
Sir.. 
Please make donation features for premium version of play!  Mobile
On playstore/appstore please, we want to help this project PLAY! mobile
Sorry bad english

### CODE REVIEW

**Comment by Bakery04** [comment]
Bukan Begitu Cara Req

**Comment by BenNottelling** [comment]
Donation options are here:
[https://purei.org/about.php](https://purei.org/about.php)

**Comment by Bakery04** [comment]
BenNottelling
Donation On Play Store ?

**Comment by SweetGTA** [comment]
> BenNottelling
> Donation On Play Store ?

Yes... 
Like Premium Version Of Play! Thats will be worth to help this project

**Pull request closed without merging**
