### PR TITLE
Fix 32-bit linux name

### PR DESCRIPTION
**Pull request by phcoder**
Fix linux name for it to be picked up by packaging

### CODE REVIEW

**Comment by gouchi** [comment]
@jpd002 @Zer0xFF will it possible to merge this PR ?

As indeed, it is not pick up by the buildbot for [x86](https://buildbot.libretro.com/nightly/linux/x86/latest/).

Thank you for your help.

**Comment by jpd002** [comment]
Thanks for the nudge and thanks for the contribution!

**Comment by Felipefpl** [comment]
@jpd002 - Btw, arent some of the other PRs elligible for submission? I'm curious about the reason why they werent submitted.

**Comment by gouchi** [comment]
> Thanks for the nudge and thanks for the contribution!

Thank you and it is now [available on the buildbot](https://buildbot.libretro.com/nightly/linux/x86/latest/) ;)

**Pull request merged**
