### PR TITLE
Conversion to storage-friendly low-bandwidth database

### PR DESCRIPTION
**Pull request by LoungeKatt**
Database converted to class with provider for easy access.
Network usage minimized through per-item on-demand calls.
Images are stored by game ID and cache can be cleared.
The database has been versioned to allow updating the user database from an included version.
Cache has been moved to external storage to decrease installed size.

### CODE REVIEW

**Comment by LoungeKatt** [comment]
Git doesn't track moving functions across files, so this is only really 2/3 changed. TheGameDb was renamed to TheGamesDb to mirror the source, so it is hard to track the changes. Instead of accessing the database for specialized call functions, it establishes a helper that supports API-style database calls.

**Comment by jpd002** [comment]
Thanks. I've tried testing this and it seems to crash when trying to look up info some a game:
```
E/AndroidRuntime(30141): FATAL EXCEPTION: main
E/AndroidRuntime(30141): Process: com.virtualapplications.play, PID: 30141
E/AndroidRuntime(30141): java.lang.NullPointerException
E/AndroidRuntime(30141):        at com.virtualapplications.play.GameInfo.getGameInfo(GameInfo.java:262)
E/AndroidRuntime(30141):        at com.virtualapplications.play.MainActivity$ImageFinder.createListItem(MainActivity.java:386)
E/AndroidRuntime(30141):        at com.virtualapplications.play.MainActivity$ImageFinder.onPostExecute(MainActivity.java:485)
E/AndroidRuntime(30141):        at com.virtualapplications.play.MainActivity$ImageFinder.onPostExecute(MainActivity.java:319)
E/AndroidRuntime(30141):        at android.os.AsyncTask.finish(AsyncTask.java:632)
E/AndroidRuntime(30141):        at android.os.AsyncTask.access$600(AsyncTask.java:177)
E/AndroidRuntime(30141):        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
E/AndroidRuntime(30141):        at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(30141):        at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime(30141):        at android.app.ActivityThread.main(ActivityThread.java:5026)
E/AndroidRuntime(30141):        at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(30141):        at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(30141):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:802)
E/AndroidRuntime(30141):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
E/AndroidRuntime(30141):        at dalvik.system.NativeStart.main(Native Method)
```

Here's the last serial that's been obtained.
```
D/Play!   (30141): SLPM62462 - Gradius V.isz [SLPM_624.62]
```

**Comment by LoungeKatt** [comment]
According to that error, the database doesn't exist. That's... odd...

**Comment by jpd002** [comment]
Is it normal that the class TheGamesDB is not being referenced by any code? I've added some traces in DatabaseHelper and it doesn't see to go through there.

**Comment by Thunder07** [comment]
He is using it as [content provider](https://github.com/jpd002/Play-/pull/257/files#diff-5820a564c65b2ff5ef6dc4d20cf606f0R23) and so it's called through [contentersolver](https://github.com/jpd002/Play-/pull/257/files#diff-09c0268eba376ce025f011a4ca7c6beeR166) I've never used them before but according to [this](http://developer.android.com/reference/android/content/ContentProvider.html), its to share data between apps, which as it stands is not needed but I do see an advantage of having, for one you don't need to start a new db connection everytime you want to request data (not sure if it's any better/worst but definitely not convenient)

**Comment by LoungeKatt** [comment]
http://stackoverflow.com/a/11467214

**Comment by jpd002** [comment]
This pull is missing this: https://github.com/AbandonedCart/Play-/blob/loungekatt/build_android/AndroidManifest.xml#L55-L57

Works perfectly with that part added in the manifest.

**Comment by LoungeKatt** [comment]
Hmm, guess that never made it.

**Comment by jpd002** [comment]
Thanks! Is this PR ready to be merged?

**Comment by LoungeKatt** [comment]
Ready as it will ever be this week.

**Comment by jpd002** [comment]
Awesome! Thanks a bunch!

**Comment by Thunder07** [comment]
@LoungeKatt you still haven't added the IDs?

**Comment by LoungeKatt** [comment]
Are you seriously asking that like I was sitting around?

**Comment by Thunder07** [comment]
Ha? Well I downloaded your db and it contains no IDs, so it's either that or my sqlite reader is broken.

**Comment by LoungeKatt** [comment]
Reader must be broken.

**Comment by Thunder07** [comment]
I'm referring to GameID after _Id 25 it's empty

**Comment by LoungeKatt** [comment]
Yes, only 25 have been completed. 25 of the 0 that would have been done. Considering how much other stuff was done, I hardly think there is much room to nitpick.

**Comment by Thunder07** [comment]
Well... Isn't that the main reason we added the db initial... But still I guess elastic search will manage to improvise.

**Comment by LoungeKatt** [comment]
Since I don't really see a point in justifying how I spend my time, iOS could use the attention.

**Pull request merged**
