### PR TITLE
iLink improvements

### PR DESCRIPTION
**Pull request by kernle32dll**
Some collected things I had laying around. Mostly derived from debugging some OPL stuff months ago.

### CODE REVIEW

**Comment by jpd002** [comment]
Thanks for this!

**Comment by Yagami2002** [comment]
Source/iop/Iop_Ilink.cpp

**Comment by Yagami2002** [comment]
Source/iop/Iop_Ilink.cpp

**Comment by Yagami2002** [comment]
`[Source/iop/Iop_Ilink.cpp](https://github.com/jpd002/Play-/pull/1184#issuecomment-1079926830) `

**Review by Yagami2002 — COMMENTED** [review]
git checkout main 
git merge --no-ff Yagami2002-patch-1 
git push origen principal

**Pull request merged**
