### PR TITLE
Automatic file identification and boxart

### PR DESCRIPTION
**Pull request by LoungeKatt**

### CODE REVIEW

**Comment by Thunder07** [comment]
This is the same pull ya?

I need to run out now, so I'm making comments without checking the code.
The image loading seems so, probably should cache the cover, if you do, then maybe you should check the cache before checking online and avoid online if found.
The game info window is nice, but should probably be a long click option (Info, Lunch), a normal click should just lunch the game.
There should be an option to refresh in the menu context, the one in setting seems hidden, maybe that should delete cache too but this refreshes the current folder/research. (again didnt check the code).
when you're offline and have no cached  images (even if you do and there is missing images, elfs for e.g), you can't tell which is which, so a list like format with side thumbnail would probably be best.

I've mentioned the lunch crash, initially i though it was the commits, then I thought it was a separate issue, but now with a full reclone, the issue persist (it does have something to do with virtual controls, but a quick skim revealed nothing).

there are the same log from yesterday for reference:
lunch crash: http://pastebin.com/cmZqyGQU
elf load crash: http://pastebin.com/SJ1xvLCE

**Comment by LoungeKatt** [comment]
The launch commands are untouched so I'm not sure how that relates.

Also, how about waiting until this works to request 100 changes?

**Comment by Thunder07** [comment]
Sorry, I thought it fails just on my build so I was commenting on the rest.

**Comment by LoungeKatt** [comment]
The problem with caching is that you have an image roughly the size of a desktop wallpaper that is scaled after download. Caching it would save the full-size image or require saving the bitmap once it's scaled and then cleaning up the original. This also means you would have to get all the disk info anyway to verify the image matches the game name. You could save it against the file name, but then you couldn't change any file names or you'd be back at needing to sync.

While it isn't an emulator, CLZ Comics is an example of the two views side by side. The list looks like you put an icon on the original file list. It doesn't look like an emulator, it looks like a file browser. The purpose of a boxart view is get away from the file browser look.

Image of CLZ Comics

**Comment by Thunder07** [comment]
I get your point with the cover layout and God knows I won't have more than the one game on my phone should it ever become playable, but I'm sure people with 20+ game will hate their lives everytime they leave the house and attempt to find the game they'd play without its cover. 

Now I'm not sure if your argument is against caching or just trying to tell me it will take time, but either or its your choice. 

If I'm not mistaken that's how windows (even android gallery, my old Nokia n95 too :p ) does (use to?)  thumbnails, through names, as such when you rename a video or a picture it takes a while for it to be regenerated.

**Comment by LoungeKatt** [comment]
mMemoryCache = new LruCache<String, Bitmap>(cacheSize) {
			@Override
			protected int sizeOf(String key, Bitmap bitmap) {
				if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.HONEYCOMB_MR1) {
					return bitmap.getByteCount() / 1024;
				} else {
					return (bitmap.getRowBytes() * bitmap.getHeight()) / 1000;
				}
			}
		};
    public void addBitmapToMemoryCache(String key, Bitmap bitmap) {
		if (key != null && !key.equals(null) && bitmap != null) {
			if (getBitmapFromMemCache(key) == null) {
				mMemoryCache.put(key, bitmap);
			}
		}
	}

	public Bitmap getBitmapFromMemCache(String key) {
		return mMemoryCache.get(key);
	}

That is roughly how to cache using included APIs, but it goes by a key that is usually the file name. In this case, it would have to be because you aren't retrieving the title. 

That is why I perform a network check before attempting to retrieve game details. No data means it doesn't even attempt to connect, and it does differentiate between wifi or mobile network, because unlimited plans don't exist anymore. Downside being you are left with just the file name.

Ideally, the database needs to be shipped in the application, since disks don't include the box image.

**Comment by LoungeKatt** [comment]
I need to contest to a gridview. This gridlayout is finicky.

**Comment by LinkofHyrule89** [comment]
On my concept I used a gridlayout and put a bunch of image buttons inside of it. However the "cards" they showed in this example could be a better option. Although I don't know that we want it to be like individualized rows if that makes sense as much as a connected chunk like on the Leanback launcher. http://ptrprograms.blogspot.com/2014/07/creating-media-app-for-androidtv.html

**Comment by LoungeKatt** [comment]
Gridlayout works fine with API 21 and predefined images in predetermined rows. It was never made to load a variable number of items at runtime, though.

Android TV is just a minor consideration. It is nice to support it, but it's only a fraction of the users. The entire UI shouldn't hinge on supporting the hardware of 1 in 1000 users.

**Comment by LinkofHyrule89** [comment]
Yeah I definitely agree there should be slightly different variation for Tablets & Android TV. What maybe we can do is have a loading logo to give it time to load the data that seems to be the trend recently.

**Comment by LinkofHyrule89** [comment]
Mmm app drawer :P

**Comment by jpd002** [comment]
@LoungeKatt I've seen the screen shots on G+, looking pretty good :+1: How do you want to proceed for the merge? I see that you are still pushing commits, do you want me to wait till you're done before I merge anything?

**Comment by LoungeKatt** [comment]
Yes, thanks. There's one minor issue to resolve.

**Comment by LoungeKatt** [comment]
And that wraps it up. I need to test this on the default DPI, though.

It will also probably need a secondary layout for the larger screens (for bigger icons / more columns)

**Comment by LoungeKatt** [comment]
https://lh4.googleusercontent.com/-VDpeX8S425s/Vak0wubvmOI/AAAAAAAACZ8/gAQ2AcHC3yU/w734-h1304-no/15%2B-%2B1
image

**Comment by Thunder07** [comment]
@LoungeKatt have you tried it without cover (net off), I tried the apk you posted but the names hang a mile below the cover.

**Comment by LoungeKatt** [comment]
Thanks. That was just after the original gridlayout. The text is now written on the bottom of the image and expands upward.

**Comment by LinkofHyrule89** [comment]
@LoungeKatt Yeah from what I understand usually you make a layout for phones, one for tablets, and one for TVs. It's actually really cool you can use the same app for all three though.

**Comment by LoungeKatt** [comment]
ic_logo

**Comment by Thunder07** [comment]
Good to know, I was just gonna say we need that icon NOW!

**Comment by LinkofHyrule89** [comment]
Looks awesome I think my only two critiques are make sure to use the latest navigation bar and menu button and also I'm sure you already fixed this but the icon and Play! text look a bit redundant. Incredibly excited to try it out on my tablet!

http://www.android-developers.blogspot.com/2015/05/android-design-support-library.html?linkId=15657197

**Comment by Fadi5555** [comment]
The icon now becoming more beautiful

You are so active with this project
Keep going.

**Comment by LinkofHyrule89** [comment]
Bro you're pretty much on a roll. At this rate you'll be done with the main gui before I get back from work tonight.

**Comment by jpd002** [comment]
I've tried your changes and I'm getting that stack trace:
```
E/AndroidRuntime( 7447): FATAL EXCEPTION: main
E/AndroidRuntime( 7447): Process: com.virtualapplications.play, PID: 7447
E/AndroidRuntime( 7447): java.lang.NullPointerException
E/AndroidRuntime( 7447):        at com.virtualapplications.play.GamesDbAPI.getValue(GamesDbAPI.java:250)
E/AndroidRuntime( 7447):        at com.virtualapplications.play.GamesDbAPI.onPostExecute(GamesDbAPI.java:169)
E/AndroidRuntime( 7447):        at com.virtualapplications.play.GamesDbAPI.onPostExecute(GamesDbAPI.java:47)
E/AndroidRuntime( 7447):        at android.os.AsyncTask.finish(AsyncTask.java:632)
E/AndroidRuntime( 7447):        at android.os.AsyncTask.access$600(AsyncTask.java:177)
E/AndroidRuntime( 7447):        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
E/AndroidRuntime( 7447):        at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 7447):        at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime( 7447):        at android.app.ActivityThread.main(ActivityThread.java:5026)
E/AndroidRuntime( 7447):        at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 7447):        at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime( 7447):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:802)
E/AndroidRuntime( 7447):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
E/AndroidRuntime( 7447):        at dalvik.system.NativeStart.main(Native Method)
```

I've outputted the gameData variable and I'm getting a bunch of:

```
W/Play!   ( 7695): <?xml version="1.0" encoding="UTF-8" ?>
W/Play!   ( 7695):
W/Play!   ( 7695): <Data>
W/Play!   ( 7695): <baseImgUrl>http://thegamesdb.net/banners/</baseImgUrl>
W/Play!   ( 7695): </Data>
```

I can trace other information if you need to.

**Comment by LinkofHyrule89** [comment]
So I found some really helpful stuff. First off here is how to get the newest version material style navigation drawer with animated menu button. The new material app drawer looks really sexy :P https://github.com/codepath/android_guides/wiki/Fragment-Navigation-Drawer 

Secondly I found something that will make things a ton easier for pulling game box art, description, rating, and basically all the information about each game based on their ID instead of having to search on the website via the name. http://users.skynet.be/fb119101/temp/ps2list.database.zip I descovered it from this project which as far as I can tell is open source and might have some useful code for both the Android and PC version of the emulator. http://psx-scene.com/forums/f150/app-automatically-get-arts-ps2list-v2013-08-03-a-72876/

In the database in the zip which is basically just a text file you can open in Notepad++ or whatever it contains this kind of format "Army Men: Sarge's Heroes 2 | SLUS_201.32 | NTSC-U | Playstation 2 | http://www.vgarchive.org/game/army-men-sarges-heroes-2-ps2-usc | March 1, 2001 | Teen - ESRB | 3DO | 3DO | North America | Action | 790561509219 | SLUS-20132 |  |  |  | EXT_NET | http://media2.vgarchive.org/boxart/23-500m.jpg |  | http://media2.vgarchive.org/screens/000000026-500m.jpg |  |  |  |  |  |  |  |  |" I added spaces on either side of the | for better readability but I'm sure you can see this database is incredibly useful.

**Comment by LoungeKatt** [comment]
Doesn't the new material drawer require API 21 and fragments?

The database should probably be in db form so it doesn't have to be full parsed to get one entry. Besides, it needs to have source that is open to the public to be open source, otherwise you need permission from the author to both include it and distribute it.

**Comment by LinkofHyrule89** [comment]
From what I understand the drawer is able to be used all the way back to gingerbread I'll have to gather more information. I think your right I was going to double check if it was open source but the website is down now. However I found a newer project with online databases and what looks like an API http://oplmanager.no-ip.info/site/index.php http://oplmanager.no-ip.info:85/OplManagerServiceV1.asmx definitely want to talk to the developer to see if we can maybe use it for the project but I don't imagine he'd have a problem with it.

**Comment by LoungeKatt** [comment]
It's really up to @jpd002. That one is a pretty big design choice.

**Comment by Thunder07** [comment]
@LinkofHyrule89 the database you listed seems complete, around 1500 games were released for the PS2 (with different all regions it probably adds up to 4500 which is listed) but the site with the hosted images hasn't been maintained since 2008, so I wouldnt trust it to stay up.

@LoungeKatt I was looking at thegamedb api, there is actually an api to list all the game for a specific platform [PS2](http://thegamesdb.net/api/PlatformGames.php?platform=sony+playstation+2), though its in xml, it can easily be converted into db and maybe hosted on purei.

the downside of this method is the search has to be down programmically inside of using the sites (potentially better) search engine.

this is a long shot, but what if we parsed both db from LinkofHyrule89 & thegamesdb cross match and add SLUS code to thegamesdb saving it as sqlite, the you can avoid search for the game through name and instead use the code, this will 1, speed up the search (assuming we can access the iso fast enough to get the game code name) since its done offline, and even when it comes to caching you'd save the image based on code name (I think maybe gamedb id instead, since different games from different region would share the gamedb id but not the game code).

**Comment by Thunder07** [comment]
I've just done parsing and cross-referencing, It managed to match 1119 out of 1680 from thegamedb to ps2list.database.zip including those with multiple game codes.

those which are messing are mainly due slight variation in naming, some special editions and few of which dont exist in ps2list db, e.g (Army Men: Green Rogue vs Army Men Green Rogue)(Codename: Kids Next Door – Operation: V.I.D.E.O.G.A.M.E. vs Codename: Kids Next Door: Operation V.I.D.E.O.G.A.M.E.)

**Comment by seadil** [comment]
Another database woulf be psxdatacenter.com
http://ns348841.ip-91-121-109.eu/psxdata/psx2/sitenews2.html

**Comment by Thunder07** [comment]
@seadil ya but theirs isn't formatted in any particular way and I'd imagine it will be a hassle trying to parse html, though there's probably a tool for it out there already. ummm...

although, if we do use it, I can use it to compare the game's serial between it and ps2list.database.zip to get alternative names for cross referencing...

but even I'm not crazy enough to bother.... yet :p

**Comment by LoungeKatt** [comment]
@Thunder07 I wish it were that simple, but the terms of GamesDB would have to allow for distributing their database. The alternative would be to parse the XML in the app. You could parse it to a database and then have a fancy GUI button to refresh it on demand.

Searching a local database is cake. It's not much more code than sending off for a search.

@seadil That isn't a database so much as a list. I don't see anything about an API or even a way to retrieve it as anything other than HTML.

**Comment by Thunder07** [comment]
@LoungeKatt nice chat, I've never been good at reading policies :p

ya that works too, but isn't parsing it into a db kind the same thing as "distributing their database"?
unless you're gonna deleting when you're done... but that still defeats the whole purpose of having it locally.
assuming we solve that issue but what do you think about the cross referencing, to use the serial, it will also allow users to freely rename their games without worrying about cover mismatch or you about caching issues.

**Comment by LoungeKatt** [comment]
Parsing it on demand is going through their provided channels to assist users in obtaining a local copy, not including a hard copy of the database as part of the application. The difference being what is specifically included in the app binary.

**Comment by LinkofHyrule89** [comment]
Wow you guys are good I go to sleep and wake up to this. It looks like we probably won't need the other site at all huh? Well keep up the great work.

**Comment by LoungeKatt** [comment]
The first time you load the app, it finds all files with a matching extension. It it letting you select a game so it can set the game folder. After that, though, it's only loading the enclosing folder. It's recursive, so if you are storing the games on the root of the sdcard, every file will be "in the folder"

**Comment by LinkofHyrule89** [comment]
So as long as your games are all in the same place it doesn't matter is what you're saying?

**Comment by Thunder07** [comment]
@LinkofHyrule89 he's saying you're better off creating a separate folder and placing your stuff in it.

**Comment by LinkofHyrule89** [comment]
Yeah I understand what he was saying. I do however think that by default the folder should be set to /PLAY DATA FILES/Roms/ to help your user not be confused. Maybe give the option to move the folder to external storage if it's detected.

**Comment by LoungeKatt** [comment]
If the folder is set to Roms by default, that would mean having to install the app first, track down the location of the folder, then put everything in it to have a game list. Alternatively, they would have to be given an additional option to change the folder. Most emulators have you set the folder on the first run, but don't show you possible games.

The banner isn't showing up corrupt from the commit (https://raw.githubusercontent.com/jpd002/Play-/4d27932a9bf977bbea49aec9804bdb3d3d688dd6/build_android/res/drawable/ic_logo.png), but there was probably a conflict if you had a banner other than the one in the repo when you cherry-picked. Git doesn't really handle binary / image merge conflicts well.

**Comment by LinkofHyrule89** [comment]
Yeah the first run should just have them select the folder's location so it doesn't just show all the random files that aren't games right off the bat. 

If you look at the build_android/res/drawable/ic_banner.png in your commit it doesn't ever load and I cloned your repo into an empty folder and it was a corrupt file. The ic_logo.png isn't corrupted.

**Comment by LoungeKatt** [comment]
Wouldn't that be undoing the entire purpose of this pull (automatic file identification)?

Looks like I clicked on the logo. I bet it saved the PSD as a PNG without actually changing the file type.

**Comment by LinkofHyrule89** [comment]
I suppose that's true in which case I still say it should just look in the file for the game id to only show game files LOL. I guess just do what you think is best I'm just thinking about what random ignorant users are going to think with all these files showing that they don't understand. Anyways I don't know why but still having compile issues ugh.

**Comment by LoungeKatt** [comment]
I have to look, but if there is a way to get the game id that wouldn't crash when it's the wrong file, that could eliminate selecting a folder altogether. There'd be no point having someone tell the app what it already knows.

For now, I think it may be the presentation of the files that is confusing. I am testing having the first selection look more like a file browser.

**Comment by LinkofHyrule89** [comment]
Yeah that's what I've been meaning to say. To a normal users they expect to see games and only games and only ones they themselves placed there. Other apps apparently use .bin files and so they show up and it's like what they heck is this game I didn't put on my device? You have to assume your users are not as tech savy as you because if you don't it's just going to cause problems.

**Comment by Thunder07** [comment]
@LoungeKatt I was looking at the code, it seems to check for system.cnf the disk has to be loaded through the virtual machine 1st, so a straight call to loaddisk to check a number of disks isn't effective.

@jpd002 maybe you can make out lives easier, since you already understand the code...
is there a quick way we can get the elf name from a disk without having to go through the virtual machine?

**Comment by jpd002** [comment]
@LoungeKatt Thanks for the crash fix. I've tested it and it works well now. I've found a small problem
when rotating from landscape to portrait on my device:

test

@Thunder07 There's no fast way, but it would be easy to write a native function that opens up a disk image and spew a game ID if it's a valid PS2 game. I can write that function if you need it (can't give any ETA though since I've got other things going on right now).

**Comment by LoungeKatt** [comment]
@LinkofHyrule89 The target market plays a big part to determine how educated the typical user will be. Most emulators have a following of primarily tech savvy individuals, since the requirements to play a ROM are that you have somehow ripped it from a disk. If they could follow the instructions required to do that, they will be capable enough to find a game in a list of files. 

@jpd002 Yeah, right now it only supports maintaining the same orientation. I can either lock the rotation or reload the table, but reloading in the current code means syncing with GamesDB again, so that may not be the better option right now.

**Comment by Thunder07** [comment]
@jpd002 I wouldnt mind a function like that, if @LoungeKatt  decides not to use it, I'll have a look at it myself, but I'm coming close to exams so it will be atleast 2 weeks before I can start working on anything, so im on no rush.

this is the skynet ps2.zip [sqlite database](https://www.dropbox.com/s/o1mghnw5upqeoz3/skynet.db?dl=0) if needed for reference

**Comment by LoungeKatt** [comment]
I converted the GamesDB one earlier. I haven't added all that in yet, though. That is a lot of code.

**Comment by Thunder07** [comment]
If you like I can upload thegamedb that's already been crossed matched, just to give you  a starting point until the serial function comes around.

**Comment by LoungeKatt** [comment]
For now, it may be best to use just the GamesDB one. I still need to look at how that needs to be credited or whatever, since it is for the site source and there will be no site.

**Comment by Thunder07** [comment]
in the about section? "the PS2 Database and cover are courtesy of..."

**Comment by jpd002** [comment]
@LoungeKatt Well, if we want to put this in tomorrow's weekly build, I think we should lock orientation to landscape so that people don't see that problem. If you don't feel it should be in tomorrow's build, then I guess we can wait a bit.

**Comment by LinkofHyrule89** [comment]
I don't think locking orientation is a problem as long as it knows TVs are horizontal.

**Comment by LoungeKatt** [comment]
@Thunder07 I mean if there is a license that needs to be included in the assets and displayed, or is there a specific phrase that is required, or simply an author. If it is GNU GPL, then this would have to be GNU GPL as well to use it.

The license for this repository (https://github.com/jpd002/Play-/blob/master/License.txt) is a BSD.

**Comment by Thunder07** [comment]
@LoungeKatt thats as much as they mention on their [site](http://wiki.thegamesdb.net/index.php/API_Introduction)... even their [terms](http://thegamesdb.net/terms/) mention nothing... again probably because the db is community maintained and they're chill about it.
they asked if you can make a post on their forum identifying yourself as a dev that would like to use the api, but for there wording they didn't seem to mind if you didn't.

at the moment though there forum is down, so you could try FB/g+ then asking them about credit.

**Comment by LoungeKatt** [comment]
@Thunder07 That statement was in the context of adding a key system. It is also about the API and site, but not about the database itself. If you have ever had to deal with Google's brand of preventing licensing violations, any question means they delete the entire app until written permission is presented. It would be a different story posting the app on a forum or something, but Google Play is considered commercial use.

@jpd002 I'm trying to wrap it all up now, but I can't promise anything.

**Comment by LoungeKatt** [comment]
Appears to be running. Orientation locks to whatever it is when launching. Initial selection is a file list and immediately switches to box art when a file is selected (instead of launching the game right away). Menu is now the slide-out bar on the left. That part is pretty basic now, but it has room to do

GAME ITEM
GAME ITEM
GAME ITEM
Heading
----------------
SYSTEM ITEM
SYSTEM ITEM

**Comment by jpd002** [comment]
@LoungeKatt Thanks for your changes. It seems that there's still issues with the file names being displayed at the bottom of the screen (like in my previous screen shot). It happens in both portrait and landscape mode. There's 6 items in my folder and there's only 3 visible. If I place 7 items in my folder, it works fine.

**Comment by Fadi5555** [comment]
I guess the names of homebrews goes down because of that space.
I mean if can see your first picture the names goes down. Now if you can see the second one because of the row is becoming full so the names goes up and named under the picture of the homebrews.
So I think is because of the space.

**Comment by LinkofHyrule89** [comment]
Final Fantasy X seems to think it's Final Fantasy XII lol. Tetris doesn't have a box cover but who cares about tetris lol. So now with a mouse I can access the settings on they nexus player but hopefully after the mobile version is sorted Android TV is next. Anyways amazing job making my dreams come true.

**Comment by LoungeKatt** [comment]
Apparently the relativelayout is considering the entire screen parent instead of just the tablerow it's in. I guess alignToBottom is less likely to spaz out.

**Comment by LoungeKatt** [comment]
This should be the initial file browser

screenshot_2015-07-19-03-57-47

And the most recent commit should fix the text boxes when no details are available

**Comment by jpd002** [comment]
Thanks, that fixed the problem I had. Well, I think it's a pretty good start for the file browser, so, I'm merging this in for tomorrow's release.

**Pull request merged**
