### PR TITLE
prepare desktop for flatpak

### PR DESCRIPTION
**Pull request by Zer0xFF**
related: https://github.com/jpd002/Play-Dependencies/pull/32 #1122 

relevant config: https://gist.github.com/Zer0xFF/c0e3187a94cad177941d03fa9b42a4c2

as is, this would work fine, though flatpak prefers to separate app config from non-flatpak apps,
haven't the change to check this out, but I believe flatpak provides a sandboxed data directory that we cn use.

### CODE REVIEW

**Comment by j8r** [comment]
Note that this not strictly required to get the Flatpak packages working.
This modifications can be done in the build process, in the `post-install` step.

**Comment by j8r** [comment]
In my opinion the first commit should not be merged as-is. The `Play` named makes more sense than `org.purei.play`. The renaming will be done in the Flatpak build.
For the 512x512 icon is welcome though, maybe smaller ones may be welcome too - have to check this out.

**Comment by Zer0xFF** [comment]
those names are just names, they dont make any different to the operation of either appimage or flatpak, so I dont see any harm in just going with 1 standard.

while the `post-install` can used to "fix" this, i find it redundant adding an extra step to the build system, when it can be avoided.
note, that this cmake step will run regardless of flatpak or not, so we might as well standardise it and keep it consistant

**Comment by Zer0xFF** [comment]
the dash doesnt really make sense., since its meant to be `!` but thats not a valid repo name so github converts it to a dash, and its definitely not going to be a valid package name. as for `Play` vs `play`, as i said, unix prefers lower case, which is how i made my decision, jpd002 can override that decision if he likes as I dont mind either way.

**Comment by jpd002** [comment]
If the doc has a capital first letter for the example app name, then, let's make our package name `org.purei.Play`. The `-` as @Zer0xFF mentioned doesn't belong in the name.

**Comment by j8r** [comment]
Related to the application ID conventions, I just found this https://docs.flatpak.org/en/latest/conventions.html?highlight=conventions#application-ids

**Comment by jpd002** [comment]
Thanks a bunch for this!

**Comment by Zer0xFF** [comment]
@j8r I've prepared the flathub repo request, you can check it out here https://github.com/Zer0xFF/flathub/tree/new-pr

**Comment by Zer0xFF** [comment]
@j8r I've prepared the flathub repo request, you can check it out here https://github.com/Zer0xFF/flathub/tree/new-pr
if im missing anything, please let me know., ill send the request once #1194 is merged.

**Pull request merged**
