### PR TITLE
Update AppConfig.cpp "Portable Mode"

### PR DESCRIPTION
**Pull request by Aynshe**
Add a "portable.txt" file to the root of Play to use the "Play Data Files" folder in the program folder. Or change the folder name and/or path by editing "portable.txt.

### CODE REVIEW

**Comment by jpd002** [comment]
Hey! Thanks for this!

Checking for `portable.txt` next to the emulator's exe path to make the emu portable makes sense, but I don't like the reading of the contents of the file to figure out the path. Paths can have unicode chars in them, so, it makes them a bit annoying to read if it's something the user can input manually. I would get rid of that code.

**Comment by Aynshe** [comment]
Hi,

Thanks for your feedback.

Yes, indeed there can be errors if a user indicates a bad path.

This is why by default the portable.txt file must be empty, change the path is optional to mount the custom path other than the executable folder.

**Comment by Aynshe** [comment]
I come back to you to find out if I understood your answer correctly (English is not my language and I use google trad).

Are you going to take the code proposal into account and edit it to remove the option that allows you to choose another disk path or if I should offer you the code cleaned of the part of the code that does not suit you?

**Comment by jpd002** [comment]
On peut faire en français pour simplifier les choses 😄 

Oui, je préfèrerais que vous changiez votre contribution pour retirer le morceau de code qui lit le contenu du fichier `portable.txt`.

Merci!

**Pull request closed without merging**
