### PR TITLE
Immaturity.cpp

### PR DESCRIPTION
**Pull request by itsmachotime8**
This pull request will enable immaturity to ensue due to the wrongdoing and accusations made toward me.

### CODE REVIEW

**Comment by itsmachotime9** [comment]
@LoungeKatt Maybe you should not be so immature. I don't care who started it.

**Comment by LoungeKatt** [comment]
Just so I understand, you are doing all of this because you were falsely accused of being immature?

Watching you embarrass yourself like this only proves it wasn't wrong, just struck a nerve. Show a little respect to @jpd002. This is his project and his account you are spamming.

**Comment by itsmachotime10** [comment]
I don't recall anyone here respecting me. I was falsely accused for trying to reason with the one being immature, which unfortunately made me upset. What's happening now is payback since Jean doesn't give a fuck and for that reason everyone who associates themselves with this project is getting pestered.

**Comment by LoungeKatt** [comment]
No, you were asked not to respond to someone that could not be reasoned with. It was not about contributions or who started it, I was giving you the benefit of thinking you could be the bigger man since his posts were all racial slurs and profanity. Sadly, I was wrong. He stopped at one offensive post and you have gone on a psychotic tirade across multiple accounts. I'm sorry you felt falsely accused, but you have more than proven you do not deserve respect or you wouldn't be acting out like this.

**Comment by itsnotmachotime** [comment]
No, you called me immature and for that you are fucked, including this whole repo.

I could give a damn at this point -- nobody falsely accuses me and doesn't pay for it.

**Comment by itsnotmachinetime2** [comment]
No, you falsely accused me and for that you are all fucked.

Just the fact that you admit to not respecting me or saying I don't deserve it means I will trouble more.

**Comment by itsnotmachinetime2** [comment]
No, you falsely accused me and for that you are all fucked.

Just the fact that you admit to not respecting me or saying I don't deserve it means I will trouble more.

**Comment by itssomachotime** [comment]
No, you falsely accused me and for that you are all fucked.

Just the fact that you admit to not respecting me or saying I don't deserve it means I will trouble more.

**Pull request closed without merging**
