### PR TITLE
Fixes, small cleanups, external launcher and theme selector

### PR DESCRIPTION
**Pull request by Thunder07**
I've tried to commit each change i make to keep the commit descriptive.

I've placed theme on its own UI Settings option, since I'd like to add gradient option and transparency toggle in the feature, both pending your pre-approval.

just a small note, https://github.com/jpd002/Play-/pull/287 converts TableLayout to LinearLayout
of which i remove TableLayout completely and relay on gridview, so just something to be aware of when trying to resolve conflicts.

### CODE REVIEW

**Comment by LoungeKatt** [comment]
@jpd002 I gathered everything related to the navbar into the library, so it may not have been part of the "original" library. Technically the values could be coded into the main.xml since they are recalculated by the getStatusBarHeight() and friends to eliminate needing a reference at all.

**Comment by Thunder07** [comment]
He's technically correct.

**Comment by jpd002** [comment]
Oh, I see. Well, I'll try to untangle everything just to make sure we've got the original libraries in there.

**Comment by LoungeKatt** [comment]
https://github.com/jpd002/Play-Dependencies/pull/3 kills off anything used on this side

The remaining values are only used by https://github.com/jpd002/Play-Dependencies/blob/master/appcompat/src/ikimuhendis/ldrawer/DrawerArrowDrawable.java

**Comment by jpd002** [comment]
Is there any point in using the LDrawer library? `android.support.v7.app.ActionBarDrawerToggle` seems to be doing exactly the same thing (with the arrow animation and all).

**Comment by Thunder07** [comment]
I'll check it out, I know Google started using arrow animations in their app, so they probably have come up with a way. (actually, I'm sure the guy who made the library made it because Google started doing it, and before that was released)

**Comment by jpd002** [comment]
@Thunder07 Well, I got it working using the ActionBarDrawerToggle from appcompat. I can push the branch so you can see.

**Comment by Thunder07** [comment]
I'll get on it.

**Comment by jpd002** [comment]
@Thunder07 I just need to know if there's any reason to keep it. If not, I'll merge that branch in master and merge another branch which removes it from Dependencies.

**Comment by Thunder07** [comment]
I'm rebasing my branch to test that out, but I guess since you got the animation to work, no need you can remove it.

**Comment by jpd002** [comment]
@Thunder07 Thanks, I've removed the library.

**Comment by Thunder07** [comment]
@jpd002 this should work working as intended now.

**Comment by LoungeKatt** [comment]
FYI: By adding the external launcher without a file pattern, this has effectively triggered the emulator to appear in **every** view chooser for **every** file on the user's device. It was either extremely lazy or a pointless attempt to avoid using any of the previous code for motives other than functionality. If there was a concern with capitalization, the list should have been duplicated with a set for capitals.

**Comment by Thunder07** [comment]
or you dont know how to read a commit.

if you really dont want me talking shit about you... stop doing this.

**Comment by LoungeKatt** [comment]
It merge failed. My apologies. Besides, you will "talk shit" either way. All you really do is one feature stacked on top of 20 commits attempting to change what I did before it. It's insecurity.

**Comment by Thunder07** [comment]
i ask question, if you take them question to be sarcastic or such thats you fault, you make comments like these "It was either extremely lazy or a pointless attempt"

**Comment by LoungeKatt** [comment]
For every one real beneficial change you make, there are 5 that move something in a linear fashion or change something to a linear format. I don't think you are lazy, but it is obvious you make a lot of extravagant attempts to replace code that doesn't need replacement.

Cmon, a GridView will fix the menu navigation... You can't be that naive.

**Comment by Thunder07** [comment]
its was a suggestion, since it worked correct in a build that i used...

however the gridview was coming eitherway...
not because of the navigation menu but because it uses adaptors.
why adaptors, because they dont bring 50 item to a view, but instead only print as many as there is to be displayed on the screen and destrory the other 40 or so views until needed.

unlike your tableview, which did exactly the opposite, aka it would print all 40 to the ui but they will just be out of view.

surely, I've made 'naive' mistakes, but not once have you found a flow in my work, yet each commit you make, breaks something in my work... sometimes even in your own.

**Comment by LoungeKatt** [comment]
I admitted my statement was incorrect, immediately removed it, and apologized.

It's not a competition. It's not a comparison. It's not *my* work or *your* work.

As for adapters, you are right. Did I tell you they were bad or try to save you a couple hours by getting it in there so you could keep working on themes? Oh, you didn't realize I was doing you a favor? Maybe that's because you saw it as stealing your "thunder" when I was trying to clean up my mess so it wasn't anyone else's responsibility.

You can't claim you just asked a question and it was taken wrong seconds after saying something that starts with "if you really dont want me talking shit about you"

"Each commit you make breaks something in my work" sounds like a personal problem. If I break something in my own, I fix it. That is not your problem. Why are you spending so much time on what I'm doing and so little on doing things of your own? How much code did you submit in the last pull that was actually new and not just trying to change how I had done it? Think about that. It's why I refuse to keep working with you. It's not doing anything but setting up an outline of what you'll do next.

**Comment by Thunder07** [comment]
"How much code did you submit in the last pull that was actually new and not just trying to change how I had done it", what i do next is fix what you've broken, I've a full list of TODOs.. but whats the point of adding them in if everything is broken.

"Oh, you didn't realize I was doing you a favor?", dude, look two lines up, you just called me naive because of gridview suggestion, now you're trying to pass it as a favor, really?

and I DIDN'T ask a question this time, i made a statement, but every other time, I ask a question, and you go on and on about how i don’t know jack!

ya its a personal problem when the master branch of jpd002 is broken because of you.
note, i've not once called you out on it, because (most times, not always) I could have done a better job in the implementation the 1st time, but due to changes in your work it caused it to break in mine, so i send in a pull and fix it... but when in reality, you should have seen that what you've broken it and fix it in that same commit.
and whether YOU fix it or I do, is irrelevant, obviously if i found something broken, by someone who worked on this 20 years ago, which are probably dead now, I'll fix it and not expect them from the dead, just for that purpose.

"It's not a competition." if you truly believed that, you'd see im improving, fixing and adding thing...
but you're so focused on me editing 'your work' which ironic on that same sentence you refereed to as neither of our work, you actually forgot the meaning of what you just said.

**Comment by LoungeKatt** [comment]
I know exactly how you feel. This guy that would "be back in two weeks after exams" spent hours doing nothing but critiques and demands every time I submitted anything. Half the time I kept having to stop and change things for him, but I couldn't really test because otherwise he wouldn't STFU. It probably contributed to a lot of the same issues he later uses as fuel for insults. Oh well, he's on his own now.

**Comment by Thunder07** [comment]
keep telling yourself that.

**Comment by LoungeKatt** [comment]
Thanks. You keep working on porting your other app to Play! 
Just think, you could even do cards that flip over for the description. That'd be neat.

**Comment by Thunder07** [comment]
Didn't need your suggest or that.

**Comment by LoungeKatt** [comment]
I don't have a copy of the TODO list, so I assume that means it was already on there. Kudos.

**Comment by Thunder07** [comment]
yes, like any sane person, I had the motivation to use gridview for its intended purpose to display a gridded list (incase you missed that), I've given you the benefit of the doubt that you know what it was intended for, I'm sorry about that.
but i cant help but remember your famous quote "I don't really see a point in justifying how I spend my time~~, iOS could use the attention.~~"


as for the list, to be honest its only waiting for your pre-approval and home address, so i can send it out to you.

**Comment by LoungeKatt** [comment]
I take what you post at face value. Most is sarcasm and insults. I apologize for not taking that as meaning you know things.

**Comment by Thunder07** [comment]
this last commit should be a temporary solution and a better work around should be found.

**Comment by LoungeKatt** [comment]
A temp database of serials and "found" game ids. If no serial, check temp, if temp serial, search by it's related ID. It "associates" the serial to an ID, but doesn't alter the core table with possible mismatched values. This assumes the purpose was trying to avoid the repeat search, but not corrupt the primary table. If this was not the purpose or the concern, please disregard.

**Comment by jpd002** [comment]
@Thunder07 I feel this PR should be split in smaller parts because it touches many parts of the emulator. Maybe we could have a PR for theming stuff, another one for the separate activity and another one for the various bugfixes?

**Comment by Thunder07** [comment]
@LoungeKatt yes, that's the reason, It also meant ton tie in later with allowing the user to reset them values without resetting the entire database. 
As a whole the fix at this stage doesn't matter, purely because your suggested alternative doesn't exist, yet. 

@jpd002, sure, but if there is something you don't want to include you can cherry pick it out, it's one of the reasons I kept the commits separate. 
Anyway, If you're still around and you'd like me to do it know, I'm still in bed twisting and turning, though I should really get up.

**Comment by Thunder07** [comment]
@jpd002,
I've broken them down into 3 PR
1) UI & Theme https://github.com/jpd002/Play-/pull/289
2) External Emulator Launcher https://github.com/jpd002/Play-/pull/290
3) Database Fix https://github.com/jpd002/Play-/pull/291

**Pull request closed without merging**
