### PR TITLE
Manifest updated to begin support for Android TV

### PR DESCRIPTION
**Pull request by LinkofHyrule89**
I added a few changes so that the app will show up on the Android TV Leanback Launcher as well as declaring support for touchscreen as well as controllers.

### CODE REVIEW

**Comment by jpd002** [comment]
Thanks for the pull request! But I think it's missing `banner.png` from e2cebf0afcae6334c524b19a1d03124ec6f3589c for the manifest to work properly.

**Comment by LinkofHyrule89** [comment]
How do I do a pull request for the banner? sorry I've never really used github before.

**Comment by jpd002** [comment]
You can cherry-pick commit e2cebf0afcae6334c524b19a1d03124ec6f3589c into your `patch-1` branch and push the branch again. This will update this pull request.

**Comment by LinkofHyrule89** [comment]
Hey I sent you a message on Hangouts so if you could get on there it would be helpful thanks.

**Comment by LinkofHyrule89** [comment]
I'm still trying to figure out how to cherry pick but I think I was able to do a pull request for the banner you can accept that first and then accept the second one I think.

**Comment by LoungeKatt** [comment]
This is close, but still a little off. You need a few other tags.

**Comment by LinkofHyrule89** [comment]
Feel free to make the proper additions mostly trying to just get the app to show up on the Leanback Launcher at this point however I really want the whole project to be working with Android Stupid and Gradle so far I haven't really figured that out it's all confusing to me at this point.

**Comment by LoungeKatt** [comment]
https://github.com/jpd002/Play-/pull/90

**Pull request closed without merging**
