### PR TITLE
Add some missing vu flag related ops, catch some cfc2/ctc2 and memory access

### PR DESCRIPTION
**Pull request by unknownbrackets**
This allows the ps2autotests relating to vu0/vu1 to "struggle along" at least, and fail (but not crash.)  I changed an assert and some throws to only log.

What's your preferred way of sharing code between FSOR and FSAND?

Also, since things are basically not working, I did not heavily test these ops.  For example, I'm not totally sure FMEQ is right but it seems like it probably is.

-[Unknown]

### CODE REVIEW

**Comment by jpd002** [comment]
Nice!

For FSAND and FSOR, I would add a new function that generates the status flag value in MA_VU_Lower.cpp and call that just before doing the AND or OR operation.

**Comment by unknownbrackets** [comment]
Okay, asked because I saw `VUShared::CheckMacFlagPipeline` and wasn't sure if you wanted it in there.

-[Unknown]

**Comment by MoochMcGee** [comment]
LGTM

**Comment by jpd002** [comment]
Thanks for the changes. I moved the BuildStatusInIT function in MA_VU_Lower.cpp just to keep all the instruction implementations in one big chunk.

**Pull request merged**
