### PR TITLE
fixes compilation on pi4 aarch64 / armv7

### PR DESCRIPTION
**Pull request by ITotalJustice**
fixes a compile error as mentioned in #789 .

### CODE REVIEW

**Comment by jpd002** [comment]
Could you try building this branch for RPI: https://github.com/jpd002/Play-/tree/pi_buildfix? I think that should fix the build on all platforms.

**Comment by ITotalJustice** [comment]
Thanks for an update, sorry that I didn’t comment on this issue / pr further!

I’ll try compiling tomorrow, I’ll let you know the results.

**Comment by jpd002** [comment]
Hi! Did you get the chance to try it?

**Comment by jpd002** [comment]
We now have ARM64 CI on Travis and @Zer0xFF submitted a fix that will work on all configs (#821) . Closing this.

**Pull request closed without merging**
