### PR TITLE
Fix a typo in time formatting

### PR DESCRIPTION
**Pull request by LoungeKatt**
This was displaying 24 hour format with AM/PM (ex. 23:17 PM). 
It would either be "hh:mm" or "K:mm a", but not a combination of both.

### CODE REVIEW

**Comment by Thunder07** [comment]
I just tested the [latest](http://playbuilds.s3-us-east-2.amazonaws.com/0723ecb2/Play-release.apk) Travis build, which is the cleanup commit from `aoe2` branch and it correctly showed `03:25 PM`, any chance you're running a Samsung device? (they tend to mess with android's inner workings ALOT)

**Comment by LoungeKatt** [comment]
If you have the choice between compatibility with all devices or telling every user of the most prominent manufacturer that they "tend to mess with android's inner workings ALOT" then it seems irrational to choose the tedious route of having to explain that every time to avoid changing an "hh" to a "K".

**Comment by Thunder07** [comment]
anyway, google's own [documentation](https://developer.android.com/reference/java/text/SimpleDateFormat.html), states `h = Hour in am/pm (1-12)` while `K = Hour in am/pm (0-11)`, I've personally never seen 00:00 PM/AM being used before, but ill leave the call to Jean.

**Comment by LoungeKatt** [comment]
I am glad you understood the purpose of the change. As you said:

> it correctly showed 03:25 PM

> I've personally never seen 00:00 PM/AM being used before

Despite the contradiction, you can see where this change would not only be compatible but also a little less "unorthodox" lol

**Comment by LoungeKatt** [comment]
I was not aware of any situation where that call was yours, but thanks for permission anyway ;)

**Pull request closed without merging**
