### PR TITLE
Updated logos, icons, and banner to match blue theme colors.

### PR DESCRIPTION
**Pull request by LinkofHyrule89**
Updated resources to match the blue theme colors, updated logos, added updated banner although it would be better if the old version was updated with the new colors. Put logo and section title in header. The section title should be programmatically updated based on which section you're currently in (Unsorted, favorites, homebrew, recents, whatever). There should not be a section header shown in the navigation drawer so it's set to null so it doesn't continue to show the section header. Because I don't have a xxxhdpi device to test on I may need to go back and make that logo bigger. I also added in the optional dark purple theme that will be selectable once the theme settings are added in.

### CODE REVIEW

**Comment by jpd002** [comment]
Thanks, this is still pending approval as I still haven't made up my mind on all this. I'll give it a try to see how it looks.

**Comment by LoungeKatt** [comment]
Looks like there is an issue with the ! logos. It's almost like you have part of a box going around the left and top sides.

That Android TV logo looks bland. It might be that it's just text, but the way the ! is pushed up against the side just gives me the impression it was thrown together instead of designed.

**Comment by LinkofHyrule89** [comment]
@LoungeKatt That's why I said it would be better if you made a new banner in the OP :P 

As far as the box on the logos I'll have to look into that all I did was put text with a transparent background so nothing else should be there. They are fairly easy to resize and what not so if that's needed I can go back and do that I already did for the tablet sized one when I originally made them.

**Comment by LoungeKatt** [comment]
screen shot 2015-08-07 at 3 48 48 am

**Comment by LinkofHyrule89** [comment]
Yeah I don't really understand why it looks like that. I think the original has that problem too but it's more noticeable because it's darker. I don't really know much about SVG is there an easy way to fix that do you think?

**Comment by LoungeKatt** [comment]
http://askubuntu.com/questions/80695/how-do-i-convert-a-svg-to-a-png-using-dithering-for-gradients

Looks like it's one of those "everyone come up with a solution for the pile" issues.

**Comment by LinkofHyrule89** [comment]
Ok I'll have to look at that more when I have time I'll be driving 26 hours to Utah this week but might get some time to do it.

**Comment by LinkofHyrule89** [comment]
Fixed it manually. Good enough?
ic_launcher

**Comment by LoungeKatt** [comment]
That would work for now. I'm trying to see what's up with the svg. Illustrator doesn't like it.

**Comment by LinkofHyrule89** [comment]
Yeah idk @jpd002 made it so idk how he did it. I'll do the rest tomorrow and put them in the PR I basically just mirrored it and blurred and smudged the top line a bit.

**Comment by LoungeKatt** [comment]
I'll have to add back the ! gradient in the morning, but I think it may have been an issue with the font. That stuff behaves differently on every system, especially changing the editor.

**Comment by LoungeKatt** [comment]
icon
https://drive.google.com/a/twistedplayground.info/file/d/0BwqYl8ZE5De0LU5Zd1NEeWVPb2s/view?usp=sharing
icon-new
https://drive.google.com/a/twistedplayground.info/file/d/0BwqYl8ZE5De0ZDYxY0RWdm9Dd1k/view?usp=sharing

**Comment by LoungeKatt** [comment]
The font was converted to an outline, so that should fix the issue of exporting it without getting the extra background noise. The shadow is a little light, but I can darken that, if necessary.

**Comment by LinkofHyrule89** [comment]
OK awesome thanks I'll commit it when I get the chance.

**Comment by LoungeKatt** [comment]
No problem. Let me know if it gives you any trouble. I had a few options for exporting in SVG so I went with whatever sounded most compatible.

**Comment by LinkofHyrule89** [comment]
@LoungeKatt I updated the icons take a look at the new commit and tell me if it looks good to you. I'll make a new banner tonight.

**Comment by LinkofHyrule89** [comment]
Ugh apparently the one icon some how isn't the right size I'll fix that tonight as well.

**Comment by LoungeKatt** [comment]
@LinkofHyrule89 Clean as it could ever be. Looks good.

**Comment by LinkofHyrule89** [comment]
@LoungeKatt can you fix the icon border to be the same thickness as the original?

**Comment by LoungeKatt** [comment]
https://drive.google.com/file/d/0BwqYl8ZE5De0NVVxR0pjLUczem8/view?usp=sharing
https://drive.google.com/file/d/0BwqYl8ZE5De0c3RJS3ZSVkk2cDg/view?usp=sharing

**Comment by LinkofHyrule89** [comment]
Ready to merge now I think if it's approved :P

**Comment by LinkofHyrule89** [comment]
Correction now it's ready. I missed one small thing.

**Comment by LinkofHyrule89** [comment]
Rebasing and splitting into multiple commits.

**Pull request closed without merging**
