### PR TITLE
Support a custom image for disks without serial

### PR DESCRIPTION
**Pull request by LoungeKatt**
This will be assigned via the filename, which will be linked to the
Disk field of the image database.

### CODE REVIEW

**Comment by jpd002** [comment]
Thanks for your changes. Unfortunately, with those changes, I'm getting a crash after a clean install of the emulator (when entering the "Games" view):
```
D/Play!   (26945): SLPM62462 - Gradius V.isz [SLPM_624.62]
E/SQLiteLog(26945): (1) no such table: games
D/AndroidRuntime(26945): Shutting down VM
W/dalvikvm(26945): threadid=1: thread exiting with uncaught exception (group=0x4170bba8)
E/AndroidRuntime(26945): FATAL EXCEPTION: main
E/AndroidRuntime(26945): Process: com.virtualapplications.play, PID: 26945
E/AndroidRuntime(26945): android.database.sqlite.SQLiteException: no such table: games (code 1): , while compiling: SELECT Boxart, GameID, Serial, GameTitle, Overview, _id FROM games WHERE (Serial=? OR Serial=? OR Serial=? OR Serial=? OR Serial=? OR Serial=?)
E/AndroidRuntime(26945):        at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
E/AndroidRuntime(26945):        at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889)
E/AndroidRuntime(26945):        at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:500)
E/AndroidRuntime(26945):        at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
E/AndroidRuntime(26945):        at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
E/AndroidRuntime(26945):        at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
E/AndroidRuntime(26945):        at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
E/AndroidRuntime(26945):        at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1314)
E/AndroidRuntime(26945):        at android.database.sqlite.SQLiteQueryBuilder.query(SQLiteQueryBuilder.java:400)
E/AndroidRuntime(26945):        at android.database.sqlite.SQLiteQueryBuilder.query(SQLiteQueryBuilder.java:294)
E/AndroidRuntime(26945):        at com.virtualapplications.play.TheGamesDB.query(TheGamesDB.java:225)
E/AndroidRuntime(26945):        at android.content.ContentProvider.query(ContentProvider.java:857)
E/AndroidRuntime(26945):        at android.content.ContentProvider$Transport.query(ContentProvider.java:200)
E/AndroidRuntime(26945):        at android.content.ContentResolver.query(ContentResolver.java:461)
E/AndroidRuntime(26945):        at android.content.ContentResolver.query(ContentResolver.java:404)
E/AndroidRuntime(26945):        at com.virtualapplications.play.GameInfo.getGameInfo(GameInfo.java:225)
E/AndroidRuntime(26945):        at com.virtualapplications.play.MainActivity$ImageFinder.createListItem(MainActivity.java:374)
E/AndroidRuntime(26945):        at com.virtualapplications.play.MainActivity$ImageFinder.onPostExecute(MainActivity.java:473)
E/AndroidRuntime(26945):        at com.virtualapplications.play.MainActivity$ImageFinder.onPostExecute(MainActivity.java:307)
E/AndroidRuntime(26945):        at android.os.AsyncTask.finish(AsyncTask.java:632)
E/AndroidRuntime(26945):        at android.os.AsyncTask.access$600(AsyncTask.java:177)
E/AndroidRuntime(26945):        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
E/AndroidRuntime(26945):        at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(26945):        at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime(26945):        at android.app.ActivityThread.main(ActivityThread.java:5026)
E/AndroidRuntime(26945):        at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(26945):        at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(26945):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:802)
E/AndroidRuntime(26945):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
E/AndroidRuntime(26945):        at dalvik.system.NativeStart.main(Native Method)
```

I can give you more information if you need it.

**Comment by LoungeKatt** [comment]
I make no promises right now, I am testing the code to find a way to copy the table without copying the database or overwriting the internal copy.

**Comment by LoungeKatt** [comment]
Ok, this should now be working and avoid any issues with the table not being preset / already being present. You may need to wipe the application data on the first install to test. This will not be necessary once the database version is updated to 2 (which should be after the pull with the database update)

**Comment by jpd002** [comment]
Just seems to be missing an import for `AsyncTask` in `TheGamesDB.java`. Otherwise, everything seems to work well. If that's ok with you, I will merge the PR.

**Comment by LoungeKatt** [comment]
Go for it. The other PR with the database will force the rebuild and enable this one. Going forward, increasing the database version number (or a fresh install) will update the database. It will only merge the packaged database if the user database is empty.

**Comment by jpd002** [comment]
Thanks!

**Pull request merged**
