### PR TITLE
Android:Updated DB with the initial set of TheGamesDB IDs

### PR DESCRIPTION
**Pull request by Thunder07**

### CODE REVIEW

**Comment by LoungeKatt** [comment]
https://github.com/jpd002/Play-/blob/master/Source/ui_android/java/com/virtualapplications/play/TheGamesDB.java#L37 1 -> 2 will force an update when it's installed.

**Comment by Thunder07** [comment]
I really need to work on my git pull request/rebase skill
rebased https://github.com/jpd002/Play-/pull/267

**Comment by LoungeKatt** [comment]
git remote update; git fetch (REMOTE_NAME); git rebase (REMOTE_NAME)/master;

**Comment by Thunder07** [comment]
isn't that meant to be the same as git pull --rebase, which is what i tried and it wouldn't let me do the push, until i called git merge.

**Comment by LoungeKatt** [comment]
after that, you have to git push -f to overwrite

**Comment by Thunder07** [comment]
Last time I tried that, it force closed my pull request, is that how it's meant to work... Or that pull got corrupted/conflicted or whatever you call it.

**Comment by LoungeKatt** [comment]
It will close the pull if nothing in it is newer than the repository it is being merged to.

**Pull request closed without merging**
