### PR TITLE
Android:Game Exit Confirmation Dialog

### PR DESCRIPTION
**Pull request by Thunder07**

### CODE REVIEW

**Comment by LoungeKatt** [comment]
It looks like a standard in-game dialog, but is there even saved progress to be lost?

**Comment by Thunder07** [comment]
There isn't really a way to find out. 
As it stands, just pressing the back button on the phone would exit the game immediately, this would atleast give you the option to continue playing.

**Comment by MisterHubs** [comment]
Well, this does seem to be useful. You can accidentally hit the back button and if you didn't save in-game you will lose all progress. Yes, progress is lost if it's unsaved; there are save states available for Windows at least, but on Android there's no option yet, and you can save in-game on games I tried.

**Comment by LoungeKatt** [comment]
You may want to wait until there is a save to say you would lose it. If there are any doubts why, take a scroll through the Google+ community for questions that are answered in the first post. Imagine what will happen when people can't figure out where to save or why they can't restore one.

**Comment by Thunder07** [comment]
Haha ya lol, I guess it should just be a confirmation if you want to exit the game.

**Comment by LinkofHyrule89** [comment]
I definitely think a simple exit prompt would be helpful it seems very odd to me that there isn't one actually.

**Comment by itsmachotime5** [comment]
@LoungeKatt Wow, don't make me regret coming here. It's immature. I don't care who started it.

**Comment by jpd002** [comment]
Thanks for the PR. At some point, I'd like to have an "in-between" menu like PPSSPP with options to save/load states and change settings.

**Comment by LinkofHyrule89** [comment]
Yeah I think that would be really handy however it would be nice if it use a button (or combination of buttons) to bring it up so that you can still use the select button as the select button on controllers right now it's the back button by default but I'm pretty sure you can change that.

**Comment by jpd002** [comment]
Yeah, I was thinking of having a key binding customization menu to allow rebinding the select button.

**Comment by itsomegamachotime** [comment]
No, you falsely accused me and for that you are all fucked.

Just the fact that you admit to not respecting me or saying I don't deserve it means I will trouble more.

**Comment by itsomegamachotime** [comment]
@LoungeKatt Stop being immature. I don't care who started it.

**Comment by itssupermegamachotime** [comment]
@TwistedUmbrella Stop being immature. I don't care who started it.

**Comment by Thunder07** [comment]
Ya I figured you'd add something like that once it's ready, but I guess this is the best next thing for now.

**Comment by itssupermegamachotime** [comment]
No, you falsely accused me and for that you are all fucked.

Just the fact that you admit to not respecting me or saying I don't deserve it means I will trouble more.

**Comment by Thunder07** [comment]
I've worked in the psychiatric ward for few years, I'm sure all the guys down there would love you.

**Comment by LoungeKatt** [comment]
@Thunder07 I start to feel a little crazy after looking at code all day. I feel perfectly normal tonight.

**Comment by itssuperultimatemachotime** [comment]
No, you falsely accused me and for that you are all fucked.

Just the fact that you admit to not respecting me or saying I don't deserve it means I will trouble more.

**Pull request merged**
