### PR TITLE
Linux AppImage

### LINKED ISSUE #858: Play! RetroArch core does not load on Debian Buster
Attempting to load Play! on latest Debian results in:

```
[ERROR] Failed to open libretro core: "/home/jstolarek/.config/retroarch/cores/play_libretro.so"
[ERROR] Error(s): /home/jstolarek/.config/retroarch/cores/play_libretro.so: symbol _ZNSt10filesystem7__cxx114path5_ListC1Ev version GLIBCXX_3.4.26 not defined in file libstdc++.so.6 with link time reference
```

Not sure whether this is the right place to report RetroArch core errors - if it isn't I'd appreciate pointing me to the right place.

### PR DESCRIPTION
**Pull request by Zer0xFF**
closes #858

Tested the resulting AppImage from travis on Ubuntu 18.04
Test Retroarch Core as well

edit:
currently installing linux arch to test that

### CODE REVIEW

**Comment by jpd002** [comment]
Is this ready to be merged? No problem if you still need to test on Arch.

**Comment by Zer0xFF** [comment]
Ya sorry I haven't tested it. (setting up arch isn't as simple as I thought it'd be :/)

**Comment by Zer0xFF** [comment]
just tested on latest Arch Linux and it boot runs just fine.

Also Money on discord confirmed it works on ubuntu 19.10

**Comment by jpd002** [comment]
Great! Thanks!

**Pull request merged**
