### PR TITLE
Support external intent, Fix import, Faster loading

### PR DESCRIPTION
**Pull request by LoungeKatt**
This is used to allow applications like Hyperspin, Gamesome, etc to launch the emulator straight to a game.

https://play.google.com/store/apps/details?id=com.shieldcade.hyperspin
https://play.google.com/store/apps/details?id=com.vektor.gamesome

### CODE REVIEW

**Comment by LinkofHyrule89** [comment]
There is this app as well haven't tried it yet though. https://play.google.com/store/apps/details?id=net.floatingpoint.android.arcturus

**Comment by LinkofHyrule89** [comment]
Just downloaded that app it's super awesome and I think it'll work once this is merged. I need to know the component and action to use though to test it although it'll probably just crash since the nexus player is broken lol.

**Comment by LoungeKatt** [comment]
com.virtualapplications.play/com.virtualapplications.play.MainActivity

**Comment by LinkofHyrule89** [comment]
OK cool I'll try that once it's merged although I'm not sure if it'll so much since it crashes for everything but the demo going to try it with the demo lol.

**Comment by LinkofHyrule89** [comment]
The app launched the emulator so that probably works but since play crashes on the nexus player can't be sure. However I did get it to launch a game directly from a file browser on another device.

**Comment by jpd002** [comment]
Looks good to me, I'll merge it if it's ready to be merged.

**Comment by Fadi5555** [comment]
@jpd002 what is will be included with this weekly build? (Specially on iOS) Because today is Sunday.
I always looking for anything new.
Thanks.

**Comment by LinkofHyrule89** [comment]
@Fadi5555 as far as I'm aware most these changes are probably Android Specific however I did hear @LoungeKatt say he was going to start working on iOS soon.

**Comment by Fadi5555** [comment]
@LinkofHyrule89 oh got your point.
Well I hope that.
To be honest I really like the progress on android specially when you added the pictures for ps2 games looks fabulous.
I hope we could see all that to iOS as will.
Anyway everything from you will be appropriated.

**Comment by LinkofHyrule89** [comment]
Yeah the biggest problem with this project is the lack of developers I'm sure if there were others wanting to help with the iOS version they would appreciate the help.

**Comment by LoungeKatt** [comment]
Yeah, sorry. I was trying to diagnose an issue. Didn't see the notification.

**Comment by Fadi5555** [comment]
Yeah you're 100% right. 
Thanks for your politeness

**Comment by LoungeKatt** [comment]
@Fadi5555 This is for Android. Android is written in Java. iOS is written in Objective-C. The views for Android are XML files, while on iOS they are plists and nib files. It is like saying that because you once rode a bike, you can fly a plane. They are two different things and no amount of nagging will get anything done. It's quite the opposite. The more you post, the more time we have to spend on here reading "keep going" instead of actually working on it.

**Comment by jpd002** [comment]
@LoungeKatt Thanks for your work!

**Comment by Fadi5555** [comment]
@LoungeKatt that's a lot of information.
Thanks for telling that.

Well, about (keep going) this is a kind of respect. Also this is less thing I should to say about you guys.

We all here to share and to know as well. So we should try to help and respect each other. That's it.

**Comment by LoungeKatt** [comment]
@Fadi5555 Respect is just as much about knowing when asking becomes harassing.

**Pull request merged**
