### PR TITLE
Automatic file identification and boxart

### PR DESCRIPTION
**Pull request by LoungeKatt**
This will set present the user with a list of files that could be games on the first run. Once a file is selected, it's folder will be stored as the "game directory"

All of the games in the folder will be displayed as boxart images using GamesDB. Clicking a single file will show a dialog that gives information about the game and allows the user to launch it.

The "game directory" can be reset in settings, allowing the user to select a different file that will store the newly selected file's folder as the new "game directory"

### CODE REVIEW

**Comment by jpd002** [comment]
Thanks! That looks quite promising! I'm going to test it on my side asap.

**Comment by itsmachotime3** [comment]
How immature of a commit.

**Comment by itsmachotime4** [comment]
Don't thank a person who attacks innocents.

**Comment by LinkofHyrule89** [comment]
Really great progress. It's cool that you made it so that it pulls information about the game too I didn't think about doing that but it really makes sense reminds me a lot of how WiiFlow does it which is where I got the idea to pull box art from GameDB to begin with.

**Comment by LoungeKatt** [comment]
@itsmachotime5 The minimum legal age to join this site under COPPA is 13. If you are older than 13 and expressing yourself through profanity and harassment, you were not falsely accused of being immature.

**Comment by itsmachotime7** [comment]
@LoungeKatt I don't care who started it. Don't make me regret coming here.

**Comment by itsmachotime8** [comment]
@LoungeKatt Stop doing that; it's immature. I'll delete my comment once you delete yours.

**Comment by LinkofHyrule89** [comment]
Here is the background I made http://i.imgur.com/fTalOoU.png might need to be tested to see if it's good enough resolution but it's the recommended size for Android TV backgrounds. Also here is the SVG for the bang icon. https://paste.ee/p/CBWf0

**Comment by itsmachotime8** [comment]
@LinkofHyrule89 Stop being immature. I don't care who started it.

**Comment by Thunder07** [comment]
@LinkofHyrule89 I applied this and the app crashes everytime I press lunch and also seems to crash everytime it tried to look up an image for elf.

elf crash:http://pastebin.com/SJ1xvLCE
lunch crash:http://pastebin.com/m3MY5C6V

**Comment by LoungeKatt** [comment]
Give me a minute. I was testing after a folder was already set. It still needs to skip that part when one isn't

**Comment by LinkofHyrule89** [comment]
So I totally didn't see that someone sent me this link anyways thought I'd share it here might be able to help with the Android TV menu and such. After that's in we can access settings and other things. http://ptrprograms.blogspot.com/2014/07/creating-media-app-for-androidtv.html

**Comment by Thunder07** [comment]
Sure,
but I don't think the folder thing makes a difference, initially I had a folder selected, so both ISO images loaded correctly, but lunch crashed.
I reset the folders, and during the search it crashed, so Net off, did the search, tried to lunch elf still crashed, net back on, ran Play, crashed before i clicked anything.

@LoungeKatt sorry this is the lunch crash http://pastebin.com/cmZqyGQU

**Comment by LinkofHyrule89** [comment]
@Thunder07 it's a continued conversation from the Google+ comm I just posted it on this since it's gui related. While technically what you said is true as well I just wanted to post it in a place that I knew it wouldn't get lost.

**Comment by LoungeKatt** [comment]
We could probably do a patch9 for that background. That would solve resolution concerns.

**Comment by LinkofHyrule89** [comment]
Sounds like a plan I thought it looked ok on my TV but I mean hey if you need to use a different one it's fine it's not like it took me more than a few minutes to make it from the icon colors. I was just trying to keep a consistent theme across everything so it's not dark and blank.

**Comment by LoungeKatt** [comment]
It will be that image, just a strip of it that will stretch automagically to the size of the screen.

**Comment by itssomachotime** [comment]
@LoungeKatt 

No, you falsely accused me and for that you are all fucked.

Just the fact that you admit to not respecting me or saying I don't deserve it means I will trouble more.

**Comment by LoungeKatt** [comment]
@itssomachotime I respect your dedication and willingness to give up your entire night to entertain me.

**Comment by itssomachotime** [comment]
No, you falsely accused me and for that you are all fucked.

Just the fact that you admit to not respecting me or saying I don't deserve it means I will trouble more.

**Pull request closed without merging**
